services:
  addrgo:
    build: .
    container_name: addrgo
    restart: always
    ports:
      - '8080:8080'
    environment:
      DB_USER: admin
      DB_PASS: admin
      DB_HOST: mariadb
      DB_PORT: 3306
      DB_NAME: addrgo
      OSM_URLS: https://download.geofabrik.de/europe/germany-latest.osm.pbf
    depends_on:
      - mariadb
  mariadb:
    image: mariadb:12
    container_name: db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: addrgo
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    volumes:
      - data:/var/lib/mysql
    ports:
      - '3306:3306'

volumes:
  data:
  minio_data:
