services:
  addrgo:
    build: .
    container_name: addrgo
    restart: always
    ports:
      - '8080:8080'
    environment:
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_HOST: mariadb
      DB_PORT: 3306
      DB_NAME: addrgo
      OSM_URLS: ${OSM_URLS:-}
    depends_on:
      mariadb:
        condition: service_healthy
  mariadb:
    image: mariadb:11
    container_name: db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: addrgo
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
    volumes:
      - data:/var/lib/mysql
    ports:
      - '3306:3306'
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

volumes:
  data:
